spring:
  Jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        default_batch_fetch_size: 100
        jdbc:
          batch_size: 50
    open-in-view: false
discord:
  name: discord-feign-client
  webhook-url: ${DISCORD_WEBHOOK_URL}
fcm:
  key: ${FCM_CONTENTS}
cors:
  allowed-origins: "http://localhost:3000,http://localhost:3000"